version: '3'

services:
  workclock-core:
    image: janezs12/workclock-core
    ports:
      - "8002:3000"
    depends_on:
      - workclock-db
      - workclock-socket
      - workclock-services
    networks:
      - workclock-network
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://workclock-db:5432/workclock-db

  workclock-services:
    image: janezs12/workclock-services
    ports:
      - "8003:5000"
    depends_on:
      - workclock-db
    networks:
      - workclock-network
    environment:
      JWT_SECRET: workclock_jwt_secret
      DB_URI: workclock-db:5432
      IS_DEV: "true"

  workclock-stats:
    image: janezs12/workclock-stats
    command: >
      sh -c "sleep 10; ./main"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workclock-db
      POSTGRES_HOST: workclock-db
      POSTGRES_PORT: 5432
    ports:
      - "8005:8080"
    depends_on:
      - workclock-core
      - workclock-db
    networks:
      - workclock-network

  workclock-socket:
    image: janezs12/workclock-socket-v4
    ports:
      - "8004:4000"
    init: true
    tty: true
    depends_on:
      - workclock-redis-service
    networks:
      - workclock-network

  workclock-frontend:
    image: janezs12/workclock-frontend
    ports:
      - "8007:7000"
    networks:
      - workclock-network

  workclock-db:
    image: postgres:13
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workclock-db
    ports:
      - "8432:5432"
    networks:
      - workclock-network

  workclock-redis-service:
    image: redis

    ports:
      - "6222:6379"
    networks:
      - workclock-network

networks:
  workclock-network: