version: '3'

services:
  workclock-core:
    image: janezs12/workclock
    networks:
      - workclock-network
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - workclock-socket
      - workclock-services

  workclock-services:
    image: janezs12/workclock_services
    networks:
      - workclock-network
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  workclock-socket:
    image: janezs12/workclock-socket
    networks:
      - workclock-network
    ports:
      - "4000:4000"
    init: true
    tty: true
    depends_on:
      - redis

  postgres:
    image: postgres:13
    networks:
      - workclock-network
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image-metadata
    ports:
      - "5432:5432"

  redis:
    image: redis
    networks:
      - workclock-network
    ports:
      - "4100:6379"


networks:
  workclock-network: