version: '3'

services:
  workclock-core:
    image: janezs12/workclock-core
    ports:
      - "8002:3000"
    depends_on:
      - workclock-db
      - workclock-socket
      - workclock-services
    networks:
      - workclock-network
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://workclock-db:5432/image-metadata

  workclock-services:
    image: janezs12/workclock-services
    ports:
      - "8003:5000"
    depends_on:
      - workclock-db
    networks:
      - workclock-network

  workclock-socket:
    image: janezs12/workclock-socket
    ports:
      - "8004:4000"
    init: true
    tty: true
    depends_on:
      - workclock-redis
    networks:
      - workclock-network

  workclock-db:
    image: postgres:13
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image-metadata
    ports:
      - "8432:5432"
    networks:
      - workclock-network

  workclock-redis:
    image: redis

    ports:
      - "6200:6379"
    networks:
      - workclock-network

networks:
  workclock-network: