apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-clock-deployment-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-clock
  template:
    metadata:
      labels:
        app: work-clock
    spec:
      containers:
        - image: janezs12/workclock:1.0.2
          imagePullPolicy: Always
          name: work-clock
          env:
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://flora.db.elephantsql.com:5432/wwdvuxwy
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: wwdvuxwy
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: 9To7p1-B3HIFXW_O_RTm2qS5sWyWOhe5
          ports:
            - containerPort: 3000
              name: server

---

apiVersion: v1
kind: Service
metadata:
  name: work-clock
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: server
  selector:
    app: work-clock
