apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config2
data:
  prometheus-config.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'flask-app'
        metrics_path: /v1/metrics/
        static_configs:
          - targets: ['work-clock-services:5000']
