apiVersion: apps/v1
kind: Deployment
metadata:
  name: workclock-redis-deployment-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workclock-redis
  template:
    metadata:
      labels:
        app: workclock-redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - '[ $(df -h / | awk ''FNR == 2 {print $5}'' | cut -d"%" -f1) -lt 80 ]'
          initialDelaySeconds: 5
          periodSeconds: 10


---

apiVersion: v1
kind: Service
metadata:
  name: workclock-redis-service
spec:
  selector:
    app: workclock-redis
  ports:
    - protocol: TCP
      port: 6379
  type: ClusterIP