apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-clock-services-deployment-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-clock-services
  template:
    metadata:
      labels:
        app: work-clock-services
    spec:
      containers:
        - image: janezs12/workclock-services:latest
          imagePullPolicy: Always
          name: work-clock-services
          ports:
            - containerPort: 5000
              name: services
          env:
            - name: JWT_SECRET
              value: workclock_jwt_secret
            - name: DB_NAME
              value: wwdvuxwy
            - name: DB_URI
              value: "pgbouncer:5432"
            - name: DB_USER
              value: wwdvuxwy
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: password
            - name: SMTP_SENDER
              valueFrom:
                secretKeyRef:
                  name: smtp-sender
                  key: sender
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-passwd
                  key: passwd
          readinessProbe:
            httpGet:
              path: /v1/health/heartbeat
              port: services
            initialDelaySeconds: 50
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: work-clock-services
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      targetPort: services
  selector:
    app: work-clock-services
