apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-clock-services-deployment-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-clock-services
  template:
    metadata:
      labels:
        app: work-clock-services
    spec:
      containers:
        - image: janezs12/workclock-services
          imagePullPolicy: Always
          name: work-clock-services
          ports:
            - containerPort: 5000
              name: services
          env:
            - name: JWT_SECRET
              value: workclock_jwt_secret
            - name: DB_URI
              value: "flora.db.elephantsql.com:5432"
            - name: DB_USER
              value: wwdvuxwy
            - name: DB_PASSWORD
              value: 9To7p1-B3HIFXW_O_RTm2qS5sWyWOhe5
            - name: DB_NAME
              value: wwdvuxwy

---

apiVersion: v1
kind: Service
metadata:
  name: work-clock-services
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      targetPort: services
  selector:
    app: work-clock-services
