kumuluzee:
  name: work-clock-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://127.0.0.1:8002
    http:
      port: 3000
  datasources:
    - jndi-name: jdbc/WorkClockDS
      connection-url: jdbc:postgresql://localhost:8432/workclock-db
      username: dbuser
      password: postgres

