kumuluzee:
  name: work-clock-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:3000
    http:
      port: 3000
  datasources:
    - jndi-name: jdbc/WorkClockDS
      connection-url: jdbc:postgresql://localhost:5432/image-metadata
      username: dbuser
      password: postgres

