name: Integration

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull Docker images
        run: docker-compose pull

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 10