name: Build, test and publish docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches: ["main"]

env:
  DOCKER_IMAGE: janezs12/workclock
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  CLUSTER_NAME: wc
  REGION: us-central1
  IMAGE_TAG: 1.0.5

jobs:
  setup-build-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Update Deployment Image Tag
        run: |
          # Replace the image tag in the Deployment YAML file
          sed -i 's/{{ .Values.imageTag }}/'"${{ env.IMAGE_TAG }}"'/' ./k8s/deployment.yaml

      - name: Install
        run: mvn --show-version --update-snapshots --batch-mode clean install -DskipTests=true

      - name: Test
        run: mvn --batch-mode test

  publish-deploy:
    name: Publish docker image and deploy to GKE
    runs-on: ubuntu-latest
    needs: setup-build-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install
        run: mvn --show-version --update-snapshots --batch-mode clean install -DskipTests=true

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: Configure kubectl
        run: gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }}

      - name: Apply Kubernetes Deployment
        run: kubectl apply -f ./k8s/deployment.yaml
